model = "gpt-5.5"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
approvals_reviewer = "user"
service_tier = "default"
[projects."/home/simon"]
trust_level = "trusted"

[projects."/home/simon/dev/numerical-optimization"]
trust_level = "trusted"

[projects."/home/simon/dev/online-reinforcement-and-learning"]
trust_level = "trusted"

[projects."/home/simon/dev/sofi-lang"]
trust_level = "trusted"

[projects."/home/simon/dev/UpRank"]
trust_level = "trusted"

[projects."/home/simon/dotfiles"]
trust_level = "trusted"

[projects."/home/simon/dev/meeting-planner"]
trust_level = "trusted"

[projects."/home/simon/dev/easyleads"]
trust_level = "trusted"

[projects."/home/simon/dev/nvim/cppman.nvim"]
trust_level = "trusted"

[projects."/home/simon/dev/ap/submission1/upload"]
trust_level = "trusted"

[projects."/home/simon/Downloads"]
trust_level = "trusted"

[projects."/home/simon/dev/kundio"]
trust_level = "trusted"

[projects."/home/simon/dev/ndak14007u-applied-programming"]
trust_level = "trusted"

[projects."/home/simon/dev/portfoliooo"]
trust_level = "trusted"

[projects."/home/simon/dev/mlb"]
trust_level = "trusted"

[projects."/home/simon/Downloads/Kundio"]
trust_level = "trusted"

[projects."/home/simon/dev/codeforces-cp"]
trust_level = "trusted"

[projects."/home/simon/dev/vibe-kanban"]
trust_level = "trusted"

[projects."/home/simon/dev"]
trust_level = "trusted"

[projects."/home/simon/.local/share/openai-dictation"]
trust_level = "trusted"

[projects."/home/simon/.codex/sessions/2026"]
trust_level = "trusted"

[projects."/home/simon/dev/rework-openai-dictation"]
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[plugins."github@openai-curated"]
enabled = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining", "five-hour-limit", "weekly-limit", "total-input-tokens", "total-output-tokens"]
pet = "null-signal"
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

