# Extra autostart processes
exec-once = uwsm app -- awww-daemon --format xrgb
exec-once = uwsm app -- waypaper --restore
exec-once = uwsm app -- waybar -c ~/.config/waybar/config-minimal.jsonc -s ~/.config/waybar/style-minimal.css
