[Personal]
source        = imaps://simonwa01%40gmail.com:bqtmbqhhnidtfvbp@imap.gmail.com:993
outgoing      = smtp://simonwa01%40gmail.com:bqtmbqhhnidtfvbp@smtp.gmail.com:587
default       = INBOX
from          = Simon Winther <simonwa01@gmail.com>
cache-headers = true

use-gmail-ext = true
