[Personal]
source        = imaps://simonwa01%40gmail.com@imap.gmail.com:993
source-cred-cmd = pass mail/gmail-aerc

outgoing        = smtp://simonwa01%40gmail.com@smtp.gmail.com:587
outgoing-cred-cmd = pass mail/gmail-aerc

default       = INBOX
from          = Simon Winther <simonwa01@gmail.com>
cache-headers = true

use-gmail-ext = true
